CONN T118/T118@DBMSDBII;
ALTER SESSION SET NLS_NUMERIC_CHARACTERS=".,";
SET ECHO OFF;
SET PAGESIZE 0;
SET LINESIZE 135;
SET FEEDBACK OFF;
SPOOL 'file.sql';
SELECT DECODE('2015-10-02', NULL, 'Unknown', TO_CHAR(1))
FROM dual;
SPOOL OFF;
EXIT;